### ISSUE TITLE
Tinkerforge DualRelay - Rules example

### ISSUE THREAD

**Issue by Korlawulki** [theoweiss/openhab-tinkerforge-configuration-examples#8]
The documentation of the Tinkerforge DualRelay bricklet does not show a valid example for a rules file. Instead, a copy of a rules file for DualButton is contained.

**Comment by theoweiss** [comment]
@Korlawulki thanks for reporting.
@sihui62 may be you can help out?

**Comment by Korlawulki** [comment]
Meanwhile, I got a working configuration. Maybe something like this could be an example for the DualRelay Bricklet rules:

```
rule "DualRelay_Example"
    when
        Item TestSwitch changed
    then
        logInfo("DualRelay1", "{}", DualRelay1.state)
        if (TestSwitch.state == ON && DualRelay1.state == OFF) 
            sendCommand(DualRelay1, ON)
        else
            sendCommand(DualRelay1, OFF)
end
```

**Comment by sihui62** [comment]
> @sihui62 may be you can help out?

Edited rule, items and sitemap in 
[https://github.com/theoweiss/openhab-tinkerforge-configuration-examples/tree/master/dualrelay](https://github.com/theoweiss/openhab-tinkerforge-configuration-examples/tree/master/dualrelay)
and changed wiki in 
[https://github.com/openhab/openhab/wiki/Tinkerforge-Binding#dual-relay-bricklet](https://github.com/openhab/openhab/wiki/Tinkerforge-Binding#dual-relay-bricklet)

**Comment by theoweiss** [comment]
Thanks @sihui62.
